// Справочник продукта: белый список того, что он берётся толковать.
//
// СГЕНЕРИРОВАНО `npm run emit`. Руками не правится:
// источник — markdown в `reference/signs/`, здесь его следствие.
// Разойдутся — упадёт питон-тест, а не пользователь.

export type RefEntry = {
  key: string; category: string; en: string;
  short: string; label: string; code: string; source: string;
};

export const ENTRIES: Record<string, RefEntry> = {
  "alla-dagar": {"key": "alla-dagar", "category": "rule", "en": "The stated hours apply on every day of the week", "short": "Hours apply every day", "label": "Time indication", "code": "T6", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "arrow-both-horizontal": {"key": "arrow-both-horizontal", "category": "rule", "en": "The sign applies on both sides of this point", "short": "Applies to the left and to the right, along the street", "label": "Extent", "code": "T11", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "arrow-both-vertical": {"key": "arrow-both-vertical", "category": "rule", "en": "The sign applies in both directions from this point", "short": "Applies both ahead of the sign and up to it", "label": "Extent", "code": "T11", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "arrow-down": {"key": "arrow-down", "category": "rule", "en": "The sign applies up to this point", "short": "Applies up to the sign, not past it", "label": "Extent", "code": "T11", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "arrow-left": {"key": "arrow-left", "category": "rule", "en": "The sign applies to the left of this point", "short": "Applies to the left of the sign", "label": "Extent", "code": "T11", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "arrow-right": {"key": "arrow-right", "category": "rule", "en": "The sign applies to the right of this point", "short": "Applies to the right of the sign", "label": "Extent", "code": "T11", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "arrow-up": {"key": "arrow-up", "category": "rule", "en": "The sign applies ahead of this point", "short": "Applies ahead of the sign, in the direction of travel", "label": "Extent", "code": "T11", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "avgift": {"key": "avgift", "category": "rule", "en": "The sign requires payment for parking during this period", "short": "Parking is not free", "label": "Fee", "code": "T16", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "avgift-erlaggs-med-mobil": {"key": "avgift-erlaggs-med-mobil", "category": "not_interpreted", "en": "The sign states that the fee is paid by phone", "short": "Fee paid by phone", "label": "Text panel", "code": "T22", "source": "разбор разработчика на собственных снимках"},
  "besokande": {"key": "besokande", "category": "rule", "en": "The sign designates these spaces for visitors", "short": "Visitors only", "label": "Text panel", "code": "T22", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "bil-personbil": {"key": "bil-personbil", "category": "rule", "en": "The sign designates these spaces for passenger cars only", "short": "Passenger cars only", "label": "Symbol panel", "code": "T8", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "boende": {"key": "boende", "category": "info", "en": "The sign notes that residents may have separate parking terms", "short": "Residents may have separate terms", "label": "Residents", "code": "T19", "source": "разбор разработчика на собственных снимках"},
  "datumintervall": {"key": "datumintervall", "category": "rule", "en": "The stated hours apply only on the dates given", "short": "Only on the dates stated", "label": "Dates", "code": "T6", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "duration-limit": {"key": "duration-limit", "category": "rule", "en": "The sign limits parking to a maximum continuous stay", "short": "Maximum continuous stay", "label": "Duration of parking permitted", "code": "T18", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "forhyrda-platser": {"key": "forhyrda-platser", "category": "rule", "en": "The sign designates these spaces as rented", "short": "Rented spaces", "label": "Text panel", "code": "T22", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "info-board": {"key": "info-board", "category": "not_interpreted", "en": "The pole also carries an operator payment board, which is not a road sign", "short": "Operator's payment board, not a road sign", "label": "Info board", "code": "", "source": "разбор разработчика на собственных снимках"},
  "jamna-veckor": {"key": "jamna-veckor", "category": "rule", "en": "The stated hours apply only in even-numbered weeks", "short": "Even weeks only — every second week", "label": "Even weeks", "code": "T6", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "landowner-plate": {"key": "landowner-plate", "category": "info", "en": "The sign names the company that manages and enforces this lot", "short": "Names the company managing the lot", "label": "Text panel", "code": "T22", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "main-parking": {"key": "main-parking", "category": "main_sign", "en": "The sign permits parking for all vehicles, subject to the general parking rules", "short": "Parking permitted, general rules still apply", "label": "Parking", "code": "E19", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "main-prohibition-parking": {"key": "main-prohibition-parking", "category": "main_sign", "en": "The sign prohibits parking", "short": "Parking prohibited", "label": "No parking", "code": "C35", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "main-prohibition-stopping": {"key": "main-prohibition-stopping", "category": "main_sign", "en": "The sign prohibits stopping and parking", "short": "Stopping and parking prohibited", "label": "No stopping or parking", "code": "C39", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "main-wayfinding-park-and-ride": {"key": "main-wayfinding-park-and-ride", "category": "main_sign", "en": "This sign points the way to a park-and-ride site; it does not permit parking here", "short": "Points the way to park-and-ride", "label": "Wayfinding to a park-and-ride site", "code": "F29", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "main-wayfinding-parking-house": {"key": "main-wayfinding-parking-house", "category": "main_sign", "en": "This sign points the way to a parking garage; it does not permit parking here", "short": "Points the way to a parking garage", "label": "Wayfinding to a parking garage", "code": "F28", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "main-zone-parking": {"key": "main-zone-parking", "category": "main_sign", "en": "The sign marks the start of a parking area", "short": "Start of a parking area", "label": "Zone sign", "code": "E20", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "main-zone-prohibition": {"key": "main-zone-prohibition", "category": "main_sign", "en": "The sign marks the start of an area where parking is prohibited", "short": "Start of a no-parking area", "label": "Zone sign", "code": "E20", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "named-weekday": {"key": "named-weekday", "category": "rule", "en": "The stated hours apply on the named weekday", "short": "Hours apply on the named weekday", "label": "Time indication", "code": "T6", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "numbered-spaces": {"key": "numbered-spaces", "category": "rule", "en": "The sign applies to the numbered spaces stated", "short": "Applies to the numbered spaces", "label": "Text panel", "code": "T22", "source": "разбор разработчика на собственных снимках"},
  "omradeskod": {"key": "omradeskod", "category": "not_interpreted", "en": "The board states an area code used by parking apps", "short": "Area code for parking apps", "label": "Info board", "code": "", "source": "разбор разработчика на собственных снимках"},
  "operator-plate": {"key": "operator-plate", "category": "not_interpreted", "en": "The sign names the parking operator", "short": "Names the parking operator", "label": "Operator plate", "code": "", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "ovrig-tid": {"key": "ovrig-tid", "category": "rule", "en": "The sign states what applies outside the hours given above", "short": "Applies outside the hours above", "label": "Text panel", "code": "T22", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "p-biljett": {"key": "p-biljett", "category": "rule", "en": "The sign requires a parking ticket; no fee is stated", "short": "Parking ticket required", "label": "Parking ticket", "code": "T20", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "p-skiva": {"key": "p-skiva", "category": "rule", "en": "The sign requires a parking disc showing the time of arrival", "short": "Parking disc required", "label": "Parking disc", "code": "T17", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "pictogram-bicycle": {"key": "pictogram-bicycle", "category": "rule", "en": "The sign designates these spaces for bicycles and class II mopeds", "short": "Bicycles and class II mopeds only", "label": "Symbol panel", "code": "T8", "source": "Transportstyrelsen, «Stanna och parkera»; T8-8"},
  "pictogram-bus": {"key": "pictogram-bus", "category": "rule", "en": "The sign designates these spaces for buses", "short": "Buses only", "label": "Symbol panel", "code": "T8", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "pictogram-electric-car": {"key": "pictogram-electric-car", "category": "rule", "en": "The sign designates these spaces for electric and plug-in hybrid vehicles that are charging", "short": "Electric and plug-in hybrids only", "label": "Charging station", "code": "T24", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "pictogram-motorcycle": {"key": "pictogram-motorcycle", "category": "rule", "en": "The sign designates these spaces for motorcycles", "short": "Motorcycles only", "label": "Symbol panel", "code": "T8", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "pictogram-truck": {"key": "pictogram-truck", "category": "rule", "en": "The sign designates these spaces for heavy goods vehicles", "short": "Heavy goods vehicles only", "label": "Symbol panel", "code": "T8", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "pictogram-wheelchair": {"key": "pictogram-wheelchair", "category": "rule", "en": "The sign designates these spaces for holders of a disabled parking permit", "short": "A disabled parking permit is required", "label": "Disabled", "code": "T7", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "place-count": {"key": "place-count", "category": "rule", "en": "The sign states how many spaces are designated", "short": "Number of spaces", "label": "Text panel", "code": "T22", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "placement-as-shown": {"key": "placement-as-shown", "category": "rule", "en": "The sign requires the vehicle to be positioned as drawn on the plate — for example at an angle to the kerb", "short": "Position the vehicle at the angle drawn on the plate", "label": "Positioning of vehicles", "code": "T21", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "privat-parkering": {"key": "privat-parkering", "category": "info", "en": "The sign marks private land and names its owner, so the lot is not evidently open to the public; it does not state the owner's terms, and those exist off the sign", "short": "Private land — the owner's terms are not stated here", "label": "Text panel", "code": "T22", "source": "разбор разработчика; lagen om kontrollavgift vid olovlig parkering (LKOP)"},
  "sarskilt-p-tillstand": {"key": "sarskilt-p-tillstand", "category": "rule", "en": "The sign requires a special parking permit", "short": "A special parking permit is required", "label": "Text panel", "code": "T22", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "stretch-metres": {"key": "stretch-metres", "category": "rule", "en": "The sign applies to the stated stretch of road", "short": "The stretch the sign covers", "label": "Length of road section", "code": "T1", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "taxa": {"key": "taxa", "category": "not_interpreted", "en": "The sign states a municipal tariff number", "short": "Municipal tariff number", "label": "Fee", "code": "T16", "source": "разбор разработчика на собственных снимках"},
  "udda-veckor": {"key": "udda-veckor", "category": "rule", "en": "The stated hours apply only in odd-numbered weeks", "short": "Odd weeks only — every second week", "label": "Odd weeks", "code": "T6", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "utanfor-markerad-plats": {"key": "utanfor-markerad-plats", "category": "rule", "en": "The sign prohibits parking outside a marked bay", "short": "Only within a marked bay", "label": "Text panel", "code": "T22", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "wayfinding-direction": {"key": "wayfinding-direction", "category": "rule", "en": "The parking facility lies in this direction; this is not the extent of a parking place", "short": "Points which way to the parking facility", "label": "Direction", "code": "F28", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "window-eve": {"key": "window-eve", "category": "rule", "en": "The stated hours apply on Saturdays and days before a Sunday or public holiday", "short": "Hours apply Saturdays and days before a holiday", "label": "Time indication", "code": "T6", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "window-red": {"key": "window-red", "category": "rule", "en": "The stated hours apply on Sundays and public holidays", "short": "Hours apply Sundays and public holidays", "label": "Time indication", "code": "T6", "source": "Transportstyrelsen, «Stanna och parkera»"},
  "window-weekday": {"key": "window-weekday", "category": "rule", "en": "The stated hours apply on ordinary weekdays", "short": "Hours apply on ordinary weekdays", "label": "Time indication", "code": "T6", "source": "Transportstyrelsen, «Stanna och parkera»"},
};
