// The general rules: what is not on the sign, and what the product does NOT
// compute.
//
// GENERATED by `npm run emit`. Never edited by hand:
// the source is the markdown in `reference/general_rules/`.
//
// They travel with the page deliberately: the reference used to arrive from a
// server, and without it the block vanished in silence - not a line to say it
// had ever been there.

export type GeneralRule = { key: string; text: string; source: string };

export const GENERAL_RULES: GeneralRule[] = [
  {"key": "blocking-others", "text": "Do not block entrances, other vehicles, or access to them", "source": "Körkortsboken på Engelska 2026"},
  {"key": "bus-stops", "text": "Keep clear of bus and tram stops", "source": "Körkortsboken på Engelska 2026"},
  {"key": "disabled-bays", "text": "Disabled bays require a permit; others may only stop to set down or pick up", "source": "Körkortsboken på Engelska 2026"},
  {"key": "junctions-and-crossings", "text": "Keep ten metres clear of junctions and pedestrian crossings", "source": "Körkortsboken på Engelska 2026"},
  {"key": "lanes-and-lines", "text": "Do not park in reserved lanes, on cycle paths, or close to a solid line", "source": "Körkortsboken på Engelska 2026"},
  {"key": "lights-in-the-dark", "text": "Show parking and tail lights when parked at the roadside in the dark", "source": "Körkortsboken på Engelska 2026"},
  {"key": "rail-and-tunnels", "text": "Do not stop at level crossings, in tunnels or on motorways", "source": "Körkortsboken på Engelska 2026"},
  {"key": "side-of-road", "text": "Park on the right-hand side, in the direction of travel", "source": "Körkortsboken på Engelska 2026"},
  {"key": "twenty-four-hours", "text": "On weekdays, park for at most 24 hours in a row in the same place", "source": "Transportstyrelsen, «Stanna och parkera»"},
  {"key": "vehicle-eligibility", "text": "Some vehicles may not use an ordinary parking space at all", "source": "Körkortsboken på Engelska 2026"},
  {"key": "visibility-and-terrain", "text": "Do not park where you block the view or sit over a crest", "source": "Körkortsboken på Engelska 2026"},
  {"key": "what-counts-as-parking", "text": "Any stop counts as parking, with four exceptions", "source": "Körkortsboken på Engelska 2026"},
];
