// The data for the browser is generated from the sources. A port of the emitters in
// `parkread/reference.py` (step 8, stage 3).
//
// The sources are the markdown of the reference, the markdown of the general rules,
// `schema/*.json` and the texts of the prompts. What is generated are four modules
// in `web/src/lib/*.data.ts`: the source is edited, the generated file follows, and
// a test guards the freshness.
//
// **What is generated is compared with the tree.** `emit.test.ts` rebuilds
// everything and compares it with what lies in the repository: let them differ and a
// test falls rather than a user. This used to prove as well that the move from
// Python had rewritten nothing along the way; there is no Python in the repository
// any more, and agreement with it to the byte is no longer required.
//
// For the developer only, and on Node only: it reads the disk and never reaches the
// build.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = fileURLToPath(new URL("../../", import.meta.url));
const NL = "\n";
const read = (path: string) => readFileSync(join(ROOT, path), "utf-8");

/** An entry of the reference: the markdown preamble plus the body of the article. */
export type Entry = {
  key: string; tokens: string; category: string; schema: string; en: string;
  source: string; body: string; short: string; label: string; code: string;
};

const HEAD = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;

/** Every entry of a directory, in order of key. */
export function readEntries(dir: string): Entry[] {
  const entries: Entry[] = [];
  for (const file of readdirSync(join(ROOT, dir)).filter((f) => f.endsWith(".md")).sort()) {
    // Line endings are normalised to `\n`, as Python did when reading text: some of
    // the articles are stored with `\r\n`, and without this neither the parsing nor
    // the text travelling into the generated file would have matched.
    const text = readFileSync(join(ROOT, dir, file), "utf-8").split("\r\n").join("\n");
    const m = HEAD.exec(text);
    if (!m) throw new Error(`${file}: no header between --- ---`);
    const head: Record<string, string> = {};
    for (const line of m[1].split("\n")) {
      const at = line.indexOf(": ");
      if (at > 0) head[line.slice(0, at)] = line.slice(at + 2);
    }
    const key = head.key ?? "";
    if (key !== basename(file, ".md")) {
      throw new Error(`${file}: key=${key} does not match the file name`);
    }
    entries.push({
      key, tokens: head.tokens ?? "", category: head.category ?? "",
      schema: head.schema ?? "", en: head.en ?? "", source: head.source ?? "",
      body: m[2].trim(), short: head.short ?? "", label: head.label ?? "",
      code: head.code ?? "",
    });
  }
  return entries.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
}

/** JSON written the way Python writes it: separators `", "` and `": "`, unicode as
 *  it is.
 *
 *  `JSON.stringify` writes without spaces, and that alone would give a different
 *  file for the same content. While the generated files are compared byte for byte
 *  with what is in the tree, the spelling has to match. */
export function pyJson(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return "[" + value.map(pyJson).join(", ") + "]";
  const body = Object.entries(value as Record<string, unknown>)
    .map(([k, v]) => JSON.stringify(k) + ": " + pyJson(v))
    .join(", ");
  return "{" + body + "}";
}

// The fields the screen takes from an entry. `body` and `tokens` do not travel: the
// first is a multi-paragraph markdown article, the second a hint for the model, and
// neither takes any part in the reading on screen. The same rule applies to the
// general rules below: their articles are written for the developer, not one of them
// is rendered, and carrying them into the browser means thousands of characters of
// prose in the bundle with no reader.
export const EMITTED_FIELDS = ["key", "category", "en", "short", "label", "code",
                               "source"] as const;

export function emitReference(): string {
  const rows = readEntries("reference/signs").map((e) => {
    const shown: Record<string, string> = {};
    for (const field of EMITTED_FIELDS) shown[field] = e[field];
    return "  " + JSON.stringify(e.key) + ": " + pyJson(shown) + ",";
  });
  const head = [
    "// The product's reference: the whitelist of what it undertakes to interpret.",
    "//",
    "// GENERATED by `npm run emit`. Never edited by hand:",
    "// the source is the markdown in `reference/signs/`, this is its consequence.",
    "// Let them drift apart and a test falls, not a user.",
    "",
    "export type RefEntry = {",
    "  key: string; category: string; en: string;",
    "  short: string; label: string; code: string; source: string;",
    "};",
    "",
    "export const ENTRIES: Record<string, RefEntry> = {",
  ];
  return [...head, ...rows, "};", ""].join(NL);
}

export function emitRules(): string {
  const rows = readEntries("reference/general_rules").map((e) =>
    "  " + pyJson({ key: e.key, text: e.en, source: e.source }) + ",");
  const head = [
    "// The general rules: what is not on the sign, and what the product does NOT",
    "// compute.",
    "//",
    "// GENERATED by `npm run emit`. Never edited by hand:",
    "// the source is the markdown in `reference/general_rules/`.",
    "//",
    "// They travel with the page deliberately: the reference used to arrive from a",
    "// server, and without it the block vanished in silence - not a line to say it",
    "// had ever been there.",
    "",
    "export type GeneralRule = { key: string; text: string; source: string };",
    "",
    "export const GENERAL_RULES: GeneralRule[] = [",
  ];
  return [...head, ...rows, "];", ""].join(NL);
}

export function emitSchema(): string {
  const sign = JSON.parse(read("schema/sign.schema.json"));
  const triage = JSON.parse(read("schema/triage.schema.json"));
  const head = [
    "// The schemas of the model's answer. GENERATED by `npm run emit`.",
    "// Never edited by hand: the source is `schema/*.json`, this is its copy.",
    "//",
    "// They are checked by our own check (`schema.ts`) rather than by a library:",
    "// the schema uses ten keywords and not one combinator (decision 124).",
    "",
    'import type { Schema } from "./schema";',
    "",
  ];
  const body = [
    "export const SIGN_SCHEMA: Schema = " + JSON.stringify(sign, null, 1) + ";",
    "",
    "export const TRIAGE_SCHEMA: Schema = " + JSON.stringify(triage, null, 1) + ";",
    "",
  ];
  return [...head, ...body].join(NL);
}

export function emitPrompts(): string {
  // The texts live as files: a prompt is the QUESTION ITSELF put to the model, and
  // editing it is easier as text than as a string in code. Its fingerprint holds
  // every saved answer, so they are copied verbatim, without a single change along
  // the way.
  const head = [
    "// The texts of the prompts. GENERATED by `npm run emit`.",
    "// Never edited by hand: the source is `prompts/*.md`.",
    "//",
    "// This is the QUESTION ITSELF put to the model: an edit changes the prompt's",
    "// fingerprint, and every saved answer stops answering it at once.",
    "",
  ];
  const body = [
    "export const TRIAGE_INSTRUCTIONS = " + JSON.stringify(read("prompts/triage.md")) + ";",
    "",
    "export const EXTRACT_INSTRUCTIONS = " + JSON.stringify(read("prompts/extract.md")) + ";",
    "",
    "export const SHAPE_HEADER = " + JSON.stringify(read("prompts/shape-header.md")) + ";",
    "",
  ];
  return [...head, ...body].join(NL);
}

export const TARGETS: { path: string; build: () => string }[] = [
  { path: "web/src/lib/reference.data.ts", build: emitReference },
  { path: "web/src/lib/rules.data.ts", build: emitRules },
  { path: "web/src/lib/schema.data.ts", build: emitSchema },
  { path: "web/src/lib/prompts.data.ts", build: emitPrompts },
];

/** What has drifted from its source. Empty means the generated files are fresh. */
export function stale(): string[] {
  return TARGETS.filter((t) => read(t.path) !== t.build()).map((t) => t.path);
}

function main(write: boolean): void {
  const outdated = stale();
  if (!write) {
    if (outdated.length) {
      console.error("out of date:\n  " + outdated.join("\n  "));
      console.error("rebuild with: npm run emit");
      process.exitCode = 1;
    } else {
      console.log("the generated data is fresh");
    }
    return;
  }
  for (const target of TARGETS.filter((t) => outdated.includes(t.path))) {
    writeFileSync(join(ROOT, target.path), target.build(), "utf-8");
    console.log("rebuilt: " + target.path);
  }
  if (!outdated.length) console.log("nothing to rebuild");
}

if (process.argv[1] && process.argv[1].endsWith("emit.ts")) {
  main(process.argv.includes("--write"));
}
